### ISSUE TITLE
Hero does not show correctly on iOS

### ISSUE THREAD

**Issue by erikjee** [rustnl/rustnl2025#10]
On the current website the here shows like this on iOS/Safari:

![WhatsApp Image 2024-09-03 at 09 03 50](https://github.com/user-attachments/assets/ca79ff05-20ce-4f06-8e5b-9f10a16dd8ea)

It should look similar to this:

![Screenshot from 2024-09-03 09-01-43](https://github.com/user-attachments/assets/171b92e9-1127-48c8-aa45-e3aa7d07f6fe)

Not 100% sure this is a iOS/Safari issue. Did not test on Android.

**Comment by jdonszelmann** [comment]
![Screenshot_20240903-093416.jpg](https://github.com/user-attachments/assets/f12b2fb7-14fb-409c-b43a-e489f456aad1)

Works as intended on Android

**Comment by tertsdiepraam** [comment]
We tracked it down to the definition of `--space-10` and that `rem` works differently on ios

**Comment by tertsdiepraam** [comment]
Also happens on mac safari

**Comment by jdonszelmann** [comment]
oof, anything we can do about it?

**Comment by tertsdiepraam** [comment]
Probably not use rem but em or px?

**Comment by erikjee** [comment]
there is rem all over the place; that is standard practise, also for safari, right? 
do you want to change it in this one specific place, `gap: var(--space-10)`?

I was trying to get my iphone to open the dev website on my laptop, to test it, but no luck

**Comment by erikjee** [comment]
@marlonbaeten can you help with this ios specific issue? See screens above.

**Comment by jdonszelmann** [comment]
note that with the change in #9 `var(--space-x)` is now just `space(x)`

**Comment by tertsdiepraam** [comment]
We can change it just there yeah. I agree that `rem` _should_ be alright. I have no idea why it isn't.
